# Generated by Django 4.0.4 on 2022-05-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1500)),
                ('url', models.CharField(max_length=1000)),
                ('salary', models.CharField(max_length=30)),
                ('contacts', models.CharField(max_length=100)),
                ('sended', models.BooleanField(default=False)),
            ],
        ),
    ]
