# Generated by Django 4.0.4 on 2022-05-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='sended',
            new_name='sent',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='contacts',
            new_name='tg_chat_id',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='salary',
        ),
        migrations.AlterField(
            model_name='employer',
            name='url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
